package com.aim.questionnaire.dao;
import com.aim.questionnaire.dao.entity.GroupEntity;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface  GroupEntityMapper{

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table project_info
//     *
//     * @mbg.generated
//     */
//    int insert(ProjectEntity record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table project_info
//     *
//     * @mbg.generated
//     */
//    int insertSelective(ProjectEntity record);
//
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table project_info
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(ProjectEntity record);
//
//
//    /**
//     * 根据项目id删除项目
//     * @param id
//     * @return
//     */
//    //int deleteProjectById(String id);
//    int deleteProjectById(ProjectEntity record);

    /**
     * 查询项目列表
     * @param projectEntity
     * @return
     */
    List<Map<String,Object>> queryProjectList(String groupName,String createdBy);

//    /**
//     * 查询全部项目的名字接口
//     * @return
//     */
//    List<Map<String,Object>> queryAllProjectName();
	
	/**
     * 查询答者
     * @param groupEntity
     * @return
     */
    List<Map<String,Object>> queryGroups();

}
