package com.aim.questionnaire.dao.entity;

import java.util.Date;

public class Questionnaire {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.id
     *
     * @mbg.generated
     */
    private String id;


    private String projectId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.user_id
     *
     * @mbg.generated
     */
    private String questionName;

    private String questionContent;
    
    private Date startTime;
    
    private Date endTime;
    
    private Date releaseTime;
    
    private String dataId;
    
    private String question;
    
    private String questionTitle;
    
    
    
    public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getQuestionTitle() {
		return questionTitle;
	}

	public void setQuestionTitle(String questionTitle) {
		this.questionTitle = questionTitle;
	}

	public String getDataId() {
		return dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getQuestionName() {
        return questionName;
    }

    public void setQuestionName(String questionName) {
        this.questionName = questionName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getQuestionContent() {
		return questionContent;
	}

	public void setQuestionContent(String questionContent) {
		this.questionContent = questionContent;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_name
     *
     * @mbg.generated
     */
    private String status;

	public Date getReleaseTime() {
		return releaseTime;
	}

	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	@Override
	public String toString() {
		return "Questionnaire [id=" + id + ", projectId=" + projectId + ", questionName=" + questionName
				+ ", questionContent=" + questionContent + ", startTime=" + startTime + ", endTime=" + endTime
				+ ", releaseTime=" + releaseTime + ", dataId=" + dataId + ", question=" + question + ", questionTitle="
				+ questionTitle + ", status=" + status + "]";
	}

	

	

}